############ Large language model config ############
# OPENAI_API_TYPE: # 'openai' or 'azure'
OPENAI_API_TYPE: "openai"

# below are for Openai
# OPENAI_KEY: # 'sk-xxxxxx'
# OPENAI_CHAT_MODEL: 'gpt-4-1106-preview' # Alternative models: 'gpt-3.5-turbo-16k-0613' (note: performance may vary)
# OPENAI_CHAT_MODEL: 'gpt-3.5-turbo-0125'
OPENAI_CHAT_MODEL: ""
OPENAI_SELF_HOST_SOURCE: "http://localhost:8001/v1"

# OPENAI_API_TYPE: 'llama'
# LLAMA_MODEL_PATH: '/tmp2/pinhank/.cache/huggingface/hub/models--TheBloke--Llama-2-7b-Chat-GGUF/snapshots/191239b3e26b2882fb562ffccdd1cf0f65402adb/llama-2-7b-chat.Q4_K_M.gguf'

# below are for Azure OAI service
AZURE_API_BASE: # https://xxxxxxx.openai.azure.com/
AZURE_API_VERSION: "2023-07-01-preview"
AZURE_API_KEY: #'xxxxxxx'
AZURE_CHAT_DEPLOY_NAME: # chat model deployment name
AZURE_EMBED_DEPLOY_NAME: # text embed model deployment name

############### DiLu settings ############
reflection_module: False # True or False
few_shot_num: 0 # 0 for zero-shot
episodes_num: 10 # run episodes
memory_path: "memories/20_mem"
result_folder: "exp/benchmark_original/"

############ Highway-env config ############
simulation_duration: 30 # step
vehicle_count: 15
other_vehicle_type: "highway_env.vehicle.behavior.IDMVehicle" #other types are: "highway_env.vehicle.behavior.DefensiveVehicle" or "highway_env.vehicle.behavior.AggressiveVehicle"
vehicles_density: 2.0
